# <u>Lesson 3b: NumPy Deep Dive</u>

Let’s dive into NumPy!

Whether you're working in data science, machine learning, scientific computing, or engineering, NumPy forms the foundation of the Python data ecosystem. Mastering NumPy's array operations is essential for working with advanced libraries such as Pandas, Scikit-learn, TensorFlow, and more.

Here we will explore how to efficiently create, manipulate, and perform operations on arrays—an essential skill for handling large datasets and performing high-performance numerical computations in Python.

In this lesson we will cover:

* What is Numpy?
* NumPy Foundations for Data Analysis with Pandas
* Array Indexing, Slicing, and Reshaping
* Array Concatenation, Stacking and Division
* Universal Functions (UFuncs)
* NumPy Agregations


### 📥 Getting the Tutorial Data

Before we begin, we need to download the example data files used in this tutorial.  
The following function will:
- Clone a GitHub repository containing the data,
- Remove any old copies to avoid conflicts,
- Copy `.txt` and `.csv` files into the current working directory.

Run the cell below to set up your environment.

This will load all the data files needed for the lesson.

In [ ]:
def fetch_data():
  import os, shutil
  cwd = os.getcwd()
  if os.path.exists("CosmicAI_WinterSchool"):
    shutil.rmtree("CosmicAI_WinterSchool")
  !git clone https://github.com/aliawofford9317/CosmicAI_WinterSchool.git
  for file in os.listdir("CosmicAI_WinterSchool"):
    if file.endswith((".txt",".csv")):
      shutil.copy("CosmicAI_WinterSchool/{}".format(file),cwd)
fetch_data()

Cloning into 'CosmicAI_WinterSchool'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 79 (delta 21), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (79/79), 8.50 MiB | 9.67 MiB/s, done.
Resolving deltas: 100% (21/21), done.


### 📚 Importing Libraries

Let’s start by importing the main libraries we’ll use in this lesson: **Numpy** and **Pandas**.

In [ ]:
import numpy as np
import pandas as pd

# <u>What is NumPy?</u>

**NumPy** (short for Numerical Python) is a foundational Python library for numerical computing. It provides efficient tools for working with large, multi-dimensional arrays and matrices, along with a wide range of high-performance mathematical functions to operate on them.

One of NumPy’s key strengths is its ability to perform fast, element-wise operations on entire arrays—making it essential for tasks that involve data manipulation, scientific computation, or machine learning.

While NumPy works on raw numerical arrays, libraries like Pandas build on NumPy’s core functionality to add more advanced data structures like Series and DataFrames.

Since Pandas is designed to integrate seamlessly with NumPy, you’ll find that most NumPy functions work directly with Pandas objects.




Here’s a clear and informative text section explaining **why NumPy is important for data science and machine learning**—suitable for a tutorial notebook:

---
# <u>Why is NumPy is important for Data Science and Machine Learning?</u>


NumPy plays a **crucial role** in the Python data science ecosystem. Its array-based computing model is at the heart of many tools used in data analysis, statistical modeling, and machine learning.

NumPy is crucial for:

- **Performance**: NumPy arrays are more memory-efficient and significantly faster than standard Python lists, especially for large datasets. This speed is essential when processing data at scale.

- **Foundation for Other Libraries**: Popular libraries such as **Pandas**, **Scikit-learn**, **TensorFlow**, and **PyTorch** all use NumPy under the hood. Understanding NumPy helps you better understand and use these tools.

- **Vectorized Operations**: NumPy supports vectorized computations—applying operations to entire arrays without the need for slow Python loops. This leads to concise, readable, and high-performance code.

- **Mathematical Tools**: NumPy offers a broad set of mathematical functions (e.g., linear algebra, statistics, random number generation) that are essential for building models and analyzing data.

- **Interoperability**: NumPy integrates well with data from many sources, including CSV files, databases, and even raw binary formats—making it a powerful tool for **data preprocessing** and **feature engineering**.

In short, mastering NumPy provides the foundation for working effectively in **data science**, **machine learning**, and **scientific computing**.

# <u>NumPy Foundations for Data Analysis with Pandas</u>

### Generating Random Data with NumPy and Pandas Series

Let’s start with a simple example to demonstrate how NumPy can be used to generate random numbers and how we can work with that data using Pandas.

In the cell below:

* We create a **random number generator** using NumPy’s `RandomState`.
* We use it to generate a small array of random integers between 0 and 10.
* We then wrap the result in a **Pandas Series**, which is a one-dimensional labeled array.

This gives us a quick and easy way to explore how NumPy and Pandas work together.



In [ ]:
# Create a container for a pseudo random generator
rng = np.random.RandomState()
# Create a Pandas Series from our random generator
series = pd.Series(rng.randint(0, 10, 4))
series

0    5
1    5
2    8
3    4
dtype: int64

### Creating a DataFrame from a NumPy Array


Now let’s generate a small Pandas DataFrame by creating a NumPy array of random integers using our random number generator.

In the cell below:

- We create a 3×4 NumPy array of random integers between 0 and 10.

- We wrap that array in a Pandas DataFrame.

- We assign custom column labels: 'A', 'B', 'C', and 'D'.

This is a helpful way to simulate sample data and see how NumPy arrays serve as the foundation for structured tabular data in Pandas.

In [ ]:
# Create a Pandas Dataframe with our Numpy random generator
# Integer numbers between 0 and 10, 3 rows and 4 columns
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                 columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  7  0  0  5
1  1  2  8  8
2  9  5  0  9

### Applying NumPy Functions to Pandas Objects

We can apply NumPy functions directly to Pandas objects while preserving the original index structure and row order.

One of the advantages of using Pandas alongside NumPy is that NumPy functions can be applied directly to Pandas Series and DataFrames. These functions operate element-wise and preserve the original index and shape of the data.



We can calculate the exponential (𝑒ˣ) of every element in a Series:

In [ ]:
# Calculate e^x, where x is every element of our array
np.exp(series)

0     148.413159
1     148.413159
2    2980.957987
3      54.598150
dtype: float64

We can also use it on a single number:

In [ ]:
# Calculate e^100
np.exp(100)

np.float64(2.6881171418161356e+43)

We can apply trigonometric functions like `np.sin()` to a DataFrame.

In [ ]:
# Calculate sin() of every value in the DataFrame multiplied by pi and divided by 4
np.sin(df * (np.pi / 4))

(1/2)+(1/2)


1.0

### Working with Multi-Dimensional NumPy Arrays
Numpy provides mutidimentional arrays, with high efficiency and designed for scientific calculations.

An array is similar to a list in Python and can be created from a list.

Array have useful atributes we can use. Lets start by defining three random arrays, a single dimension, a two dimension and a tri dimensional array.



### Creating NumPY Arrays of Different Dimensions

In the example below, we’ll use NumPy’s random number generator to create:

- A 1D array
- A 2D array
- A 3D array (also called a tri-dimensional array)

We’ll also set a random seed to ensure the results are reproducible:


In [ ]:
# Import our Numpy package
import numpy as np
np.random.seed(0) #this will generate the same random arrays every time

x1 = np.random.randint(10, size=6) # one dimension
x2 = np.random.randint(10, size=(3, 4)) # two dimensions
x3 = np.random.randint(10, size=(3, 4, 5)) # tri dimensional array

In [ ]:
# Display the 3D array
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

### Numpy Array Attributes

All NumPy arrays include several helpful attributes:

- `ndim` (number of dimensions) attribute
- `shape` the size of each dimension,
- `size` the total array size

In [ ]:
print("x3 ndim:", x3.ndim)    # Number of dimensions
print("x3 shape:", x3.shape)  # Size of each dimension
print("x3 size:", x3.size)    # Total number of elements

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


You can also inspect the **memory usage** of an array using additional attributes:

- `itemsize` shows the **size in bytes** of each individual element in the array.
- `nbytes` returns the **total memory size** of the entire array in bytes.


In [ ]:
print("x3 itemsize:", x3.itemsize, "bytes")  # Bytes per element
print("x3 nbytes:", x3.nbytes, "bytes")      # Total memory used

x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


### Creating Arrays with Numpy methods


For larger or more complex arrays, it's often more efficient to use built-in NumPy array creation functions instead of manually defining lists. NumPy provides a wide variety of methods for generating arrays with specific values, shapes, or distributions.

Below are some commonly used array creation functions:

`np.zeros()` creates an array filled with zeros. Useful for initializing arrays when the values will be assigned later.

In [ ]:
# Create a length 10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

`np.ones()` creates an array filled with ones. Common for testing, masking, or use in default initializations.


In [ ]:
# Create a 3x5 float array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

`np.full()` creates an array filled with a specified constant value.

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

`np.arange()` generates values in a range with a defined step size. Similar to Python’s built-in range() but returns a NumPy array.

In [ ]:
# Create an array filled with a linear sequence
# Start at 0, end at 20, step size 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

`np.linspace()` generates a specified number of evenly spaced values between a start and end point.

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

`np.random.random()`creates an array of uniformly distributed random values between 0 and 1.


In [ ]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

`np.random.normal()` creates an array of random values drawn from a normal distribution (Gaussian). Useful for simulating real-world variability.

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

`np.random.randint()` creates an array of random integers from a given interval.

In [ ]:
# Create a 3x3 array of random integer in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

`np.eye()` creates an identity matrix—a square matrix with ones on the diagonal and zeros elsewhere.



In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`np.empty()` creates an uninitialized array (values will be whatever is in memory). Useful when performance matters and the array will be immediately overwritten.

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])



# <u>Array Indexing,Slicing and Reshaping</u>

#### Array Indexing

Just like Python lists, NumPy arrays allow you to access and modify elements using indexing.

Here's how it works for both 1D and multi-dimensional arrays:

##### Indexing in Single-dimensional (1D) Arrays

For one-dimensional arrays, we use square brackets [ ] with the element's index (starting from 0):

In [ ]:
x1 # View the full 1D array

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0] # First element

np.int64(5)

In [ ]:
x1[4] # Fifth element

np.int64(7)

In [ ]:
x1[-6] # First element (using negative indexing)

np.int64(5)

**Note:**  Negative indexing counts from the end of the array (-1 is the last element).

##### Indexing in Multi-dimensional Arrays (i.e. 2D, 3D ect.)

We can use similar logic for multi-dimensional arrays. For these arrays, use a comma-separated format to specify indices (e.g., row and column indices for 2D arrays).

In [ ]:
x2 # View the 2D array

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 3] # Element in row 0, column 3

np.int64(4)

In [ ]:
x2[0][3] # Equivalent to x2[0, 3]

np.int64(4)

**Note:** Both x2[0, 3] and x2[0][3] will return the same result, though the former is generally preferred in NumPy for better performance and readability.

In [ ]:
x2[2, -1] #  Element in row 2, last column

np.int64(7)

We can use the same logic to change values using array indexing

##### Modifying Array Elements

You can also modify array elements directly using their index:



In [ ]:
x2[2, -1] = 2 # Change the last element of row 2 to 2

#### Sub Arrays (Slicing)


NumPy also allows you to access subsections of arrays using a slicing syntax similar to Python lists. The syntax goes as follows:

`x[start:stop:step]`

- start : the index to begin slicing (default is 0)

- stop : the index to stop before (non-inclusive)

- step : the stride or step size between elements



To demonstrate slicing techniques, let’s start by creating a simple one-dimensional NumPy array.

We’ll use np.arange() to generate a sequence of integers from 0 to 9 in the cell below.







In [ ]:
# Create a 1D NumPy array with values from 0 to 9
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Slicing Single-dimensional Arrays

In [ ]:
x[:5] # First five elements (index 0 to 4)

array([0, 1, 2, 3, 4])

In [ ]:
x[5:] # All elements starting from index 5 to the end

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7] # Elements from index 4 to 6 (stop index is non-inclusive)

array([4, 5, 6])

In [ ]:
x[::2] # Every second element (step size of 2)

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2] # Every second element starting from index 1

array([1, 3, 5, 7, 9])

We can also use a negative step value, which effectively reverses the direction of slicing. This is a convenient way to reverse an array or extract elements in reverse order.

In [ ]:
x[::-1] # Reverse the array using a negative step

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2] # # Reverse the array starting from index 5 with step size -2

array([5, 3, 1])

##### Slicing Multi-dimensional Arrays

Now let’s look at slicing in multi-dimensional arrays. The concept is similar, but we separate each dimension’s slice with a comma.

We will use the previously defined x2 array to demonstrate slicing operations on multi-dimensional arrays.





In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[:2, :3] # rows with index 0 and 1, and columns with index 0, 1 and 2

array([[3, 5, 2],
       [7, 6, 8]])

In [ ]:
x2[:3, ::2] # all rows but step size 2

array([[3, 2],
       [7, 8],
       [1, 7]])

#### Reshaping Arrays

Another common and powerful operation in NumPy is reshaping, which allows you to change the dimensions of an array without altering its underlying data.

You can use the `.reshape()` method to convert a 1D array into a multi-dimensional array—or vice versa—so long as the total number of elements remains the same.



To demonstrate this, we’ll start by creating a 1D NumPy array with 9 elements, and then reshape it into a 3 × 3 array:



In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**NOTE:** The total number of elements must remain the same when reshaping—otherwise, NumPy will raise an error.


##### Converting Between Row and Column Vectors

Another useful reshaping task is converting a one-dimensional array into a row vector or a column vector. You can do this using either `.reshape()` or `np.newaxis.`

Remember : For this to work the size of the initial array must match the reshaped array.


Row Vectors Examples

In [ ]:
import numpy as np

x = np.array([1, 2, 3])

# row vector via reshape
x.reshape(1, 3)

array([[1, 2, 3]])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

Column Vector Examples

In [ ]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

These operations are especially useful when preparing data for machine learning models or broadcasting in mathematical operations.



# <u>Array Concatenation,Stacking and Division</u>

NumPy allows you to combine arrays by concatenating or stacking them vertically or horizontally.
This is especially useful when you want to merge datasets or assemble arrays into larger, structured blocks.



The `np.concatenate()` function takes a list of arrays as its first argument and merges them along the specified axis.

We'll look at examples for both 1D and 2D arrays below.

##### Concatenating 1D Arrays

You can use `np.concatenate()` to join arrays along an existing axis.

For 1D arrays, it simply appends them end to end:

In [ ]:
x = np.array([1, 2, 3])  # First 1D array
y = np.array([3, 2, 1])  # Second 1D array

# Concatenate two arrays
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [ ]:
# we can concatenate more than one array at a time
z = [99, 88, 77]  # Third array
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 88 77]


##### Concatenating 2D Arrays

For 2D arrays, you can use `np.concatenate()` to combine:

- Rows by specifying `axis=0` (this stacks arrays vertically)

- Columns by specifying `axis=1` (this stacks arrays horizontally)


This follows the same logic as with 1D arrays, but now you control which axis the concatenation applies to.

This is useful when you're combining data tables or merging features.





We'll demonstrate both in the cells below using a simple grid.

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Concatenate along rows (axis=0)
np.concatenate([grid, grid],axis=0)  # concatenate on rows



array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Concatenate on the second axis (zero indexed)
np.concatenate([grid, grid], axis=1) # concatenate on columns



array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

##### Vertical and Horizontal Stacking

To combine arrays of different shapes or dimensions—especially when mixing 1D and 2D arrays—NumPy provides two helpful functions:

`np.vstack()` — for vertical (row-wise) stacking

`np.hstack()` — for horizontal (column-wise) stacking

These functions are especially useful when concatenation with `np.concatenate()` becomes tricky due to shape mismatches.


In [ ]:
# stack vertically
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# stack horizontally
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Split Arrays

NumPy also allows you to split arrays into multiple sub-arrays, which is especially useful when you need to divide data into sections for processing or analysis.

To do this, you can use the following functions:

`np.split()` — for splitting 1D arrays

`np.hsplit()` — for horizontal (column-wise) splitting of 2D arrays

`np.vsplit()` — for vertical (row-wise) splitting of 2D arrays

##### Spliting a 1D Array using `np.split()`

In [ ]:
x = [1, 2, 3, 99, 88, 77, 4, 5, 6] #1D Array
x1, x2, x3 = np.split(x, [3, 5]) # split at index 3 and 5, non inclusive

print(x1)  # [1 2 3]
print(x2)  # [99 88]
print(x3)  # [77  4  5  6]

[1 2 3]
[99 88]
[77  4  5  6]


*Observe* that N division/split points lead to N + 1 sub arrays. Similarly `np.hsplit` and `np.vsplit` can be used

##### Vertical (Row-wise) Splitting of 2D Arrays

- Used to split a 2D array along the rows (axis=0)

In [ ]:
# Create a 4x4 array
grid = np.arange(16).reshape((4, 4))
print(grid)

# Split vertically at row index 2
upper, lower = np.vsplit(grid, [2])
print(upper)  # First two rows
print(lower)  # Last two rows


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


##### Horizontal (Column-wise) Splitting of 2D Arrays

- Used to split a 2D array along the columns (axis=1)

In [ ]:
# Use the same 4x4 array
print(grid)

# Split horizontally at column index 2
left, right = np.hsplit(grid, [2])
print(left)   # First two columns
print(right)  # Last two columns


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# <u>Universal Functions (UFuncs) </u>

Next we will look at why NumPy is important for data science and working with arrays.

The key to making computation with NumPy very fast is using vectorized operations with NumPy, they key to this is using NumPy Universal Functions.

In the cells below, we’ll compare the performance of a traditional Python for loop with a vectorized operation in NumPy using an array containing one million values.

In [ ]:
# Traditional implementation
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

The code below takes several seconds to run. Lets run it now with a vectorized operation.

In [ ]:
# Times the operation on a large array

big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.32 s ± 565 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Now let's do the same thing with vectorized NumPy operations:

In [ ]:
# Vectorized approach
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
%timeit (1.0 / big_array)

2.08 ms ± 66.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Result: The vectorized approach is orders of magnitude faster than the traditional loop.**

This performance boost comes from NumPy’s Universal Functions (ufuncs), which are optimized C-based functions designed to execute repeated operations efficiently on entire arrays—without explicit Python loops.


##### Scalar and Array Operations
Ufuncs (universal functions) can run between scalars and arrays, two arrays, and multi dimensional arrays.

In [ ]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
# multidimensional example
x = np.arange(9).reshape((3, 3))
2 ** x


#### Arithmetic Operations

NumPy provides UFuncs for performing fast, element-wise arithmetic operations. These include addition, subtraction, multiplication, division, and more—all applied efficiently across entire arrays.

In [ ]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [ ]:
# unary functions for negation, exponentiation, and modulus
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


All these arithmetic operations are wrappers for Numpy functions

|Operator|	Equivalent ufunc |	Description |
|:--------:|:--------|:--------|
|+ |	np.add	| Addition (e.g., 1 + 1 = 2) |
|- |	np.subtract | Subtraction (e.g., 3 - 2 = 1)
|- |	np.negative |	Unary negation (e.g., -2)
|* |	np.multiply |	Multiplication (e.g., 2 * 3 = 6)
|/ |	np.divide |	Division (e.g., 3 / 2 = 1.5)
|// |	np.floor_divide |	Floor division (e.g., 3 // 2 = 1)
|** |	np.power |	Exponentiation (e.g., 2 ** 3 = 8)
|% |	np.mod |	Modulus/remainder (e.g., 9 % 4 = 1)

#### Trigonometric functions

NumPy provides a comprehensive set of trigonometric functions that operate element-wise on arrays. These functions are essential for working with angles, waveforms, and geometric computations, making them especially valuable in scientific and engineering applications.




In the example cell below, we’ll start by defining an array of angles and use NumPy to compute their sine, cosine, and tangent values.


In [ ]:
theta = np.linspace(0, np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


NumPy also includes inverse trigonometric functions—arcsin, arccos, and arctan—which are used to compute the angle (in radians) corresponding to a given trigonometric value.

These functions are especially useful when solving problems that involve recovering angles from sine, cosine, or tangent values.

In the example below, we’ll pass a set of valid input values to these inverse functions to demonstrate how they return the corresponding angles.

In [ ]:
# Define a list of values between -1 and 1 (valid input range for arcsin and arccos)
x = [-1, 0, 1]

# Apply inverse trigonometric functions
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))


x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### Exponents and logarithms

NumPy provides a variety of universal functions (UFuncs) for performing exponential and logarithmic calculations efficiently across arrays.

These functions are fundamental in many scientific and machine learning applications, such as:

- Modeling exponential growth or decay

- Transforming skewed data

- Solving equations involving powers or logs



Exponential functions such as `np.exp()` `np.exp2()`, and `np.power()` are for computing powers and growth rates.



In [ ]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

Logarithmic functions like `np.log()`, `np.log2()`, and `np.log10()` are for scaling and transforming data.

In [ ]:
# log functions
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

# <u>NumPy Agregatations </u>


NumPy also provides tools for reducing arrays—applying operations across all elements to produce a single cumulative result. These operations are particularly useful when summarizing or aggregating data.

One such tool is the `.reduce()` method, which repeatedly applies a given operation (like addition or multiplication) to all elements of the array until a single value remains.



In [ ]:
# Create a simple array of values
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

Using `np.add.reduce()` sums all elements in the array

In [ ]:
np.add.reduce(x)  # Output: 15

np.int64(15)

Using `np.multiply.reduce()` multiplies all elements together

In [ ]:
# calling reduce on multiply
# results in the product of all array elements
np.multiply.reduce(x)  # Output: 120

np.int64(120)

If you want to keep track of intermediate results instead of reducing to a single value, you can use the `.accumulate()` method.

This returns an array showing the cumulative result at each step of the operation.

In [ ]:
# Cumulative sum using accumulate
np.add.accumulate(x)  # Output: [ 1  3  6 10 15 ]


In [ ]:
# Cumulative product using accumulate
np.multiply.accumulate(x)  # Output: [  1  2  6 24 120 ]


## 🛑 End of Lesson 3b: NumPy Deep Dive

## **Please proceed to Lesson 3c: Scikit-Learn to continue the tutorial.**

Please complete the following Tasks:

- ✅ **Lesson 3 Terminology Quiz**
- ✅ **Lesson 3 Coding Exercises**

📩 Submit all solutions to your instructor once complete.