In [ ]:
def fetch_data():
  import os, shutil
  cwd = os.getcwd()
  if os.path.exists("CosmicAI_WinterSchool"):
    shutil.rmtree("CosmicAI_WinterSchool")
  !git clone https://github.com/aliawofford9317/CosmicAI_WinterSchool.git
  for file in os.listdir("CosmicAI_WinterSchool"):
    if file.endswith((".txt",".csv")):
      shutil.copy("CosmicAI_WinterSchool/{}".format(file),cwd)
fetch_data()

Cloning into 'CosmicAI_WinterSchool'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 79 (delta 21), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (79/79), 8.50 MiB | 4.98 MiB/s, done.
Resolving deltas: 100% (21/21), done.


In [ ]:
## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.
import pandas as pd

## Individual Exercise 1

Lets revist our `cereal.csv` and check some Pandas functions.





In [ ]:
cereal = pd.read_csv('cereal.csv', index_col='name')
cereal.head()

mfr type  calories  protein  fat  sodium  fiber  \
name                                                                        
100% Bran                   N    C        70        4    1     130   10.0   
100% Natural Bran           Q    C       120        3    5      15    2.0   
All-Bran                    K    C        70        4    1     260    9.0   
All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
Almond Delight              R    C       110        2    2     200    1.0   

                           carbo  sugars  potass  vitamins  shelf  weight  \
name                                                                        
100% Bran                    5.0       6     280        25      3     1.0   
100% Natural Bran            8.0       8     135         0      3     1.0   
All-Bran                     7.0       5     320        25      3     1.0   
All-Bran with Extra Fiber    8.0       0     330        25      3     1.0   
Almond Delight              14.0       8      -1        25      3     1.0   

                           cups     rating  
name                                        
100% Bran                  0.33  68.402973  
100% Natural Bran          1.00  33.983679  
All-Bran                   0.33  59.425505  
All-Bran with Extra Fiber  0.50  93.704912  
Almond Delight             0.75  34.384843

Practice: What Pandas command can you use to show the first 5 rows?

Practice: What Pandas command can you use to show the last 5 rows?


In [ ]:
cereal.head(5)

mfr type  calories  protein  fat  sodium  fiber  \
name                                                                        
100% Bran                   N    C        70        4    1     130   10.0   
100% Natural Bran           Q    C       120        3    5      15    2.0   
All-Bran                    K    C        70        4    1     260    9.0   
All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
Almond Delight              R    C       110        2    2     200    1.0   

                           carbo  sugars  potass  vitamins  shelf  weight  \
name                                                                        
100% Bran                    5.0       6     280        25      3     1.0   
100% Natural Bran            8.0       8     135         0      3     1.0   
All-Bran                     7.0       5     320        25      3     1.0   
All-Bran with Extra Fiber    8.0       0     330        25      3     1.0   
Almond Delight              14.0       8      -1        25      3     1.0   

                           cups     rating  
name                                        
100% Bran                  0.33  68.402973  
100% Natural Bran          1.00  33.983679  
All-Bran                   0.33  59.425505  
All-Bran with Extra Fiber  0.50  93.704912  
Almond Delight             0.75  34.384843

In [ ]:
cereal.tail(5)

mfr type  calories  protein  fat  sodium  fiber  carbo  \
name                                                                         
Triples               G    C       110        2    1     250    0.0   21.0   
Trix                  G    C       110        1    1     140    0.0   13.0   
Wheat Chex            R    C       100        3    1     230    3.0   17.0   
Wheaties              G    C       100        3    1     200    3.0   17.0   
Wheaties Honey Gold   G    C       110        2    1     200    1.0   16.0   

                     sugars  potass  vitamins  shelf  weight  cups     rating  
name                                                                           
Triples                   3      60        25      3     1.0  0.75  39.106174  
Trix                     12      25        25      2     1.0  1.00  27.753301  
Wheat Chex                3     115        25      1     1.0  0.67  49.787445  
Wheaties                  3     110        25      1     1.0  1.00  51.592193  
Wheaties Honey Gold       8      60        25      1     1.0  0.75  36.187559

In [ ]:
## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.


1. Can you find the average sugar content of the cereals which list the portion `cups` size as 1.0?
2. Can you find the highest and lowest calorie content of the previous selection?





In [ ]:
cereal.query("cups == 1.0")["sugars"].mean()

np.float64(6.4)

In [ ]:
cereal.query("cups == 1.0")["calories"].min(), cereal.query("cups == 1.0")["calories"].max()

(50, 150)

## Individual Exercise 2

3. How many cereals by manufacturer `G` have a higher calorie content than 100?

In [ ]:
cereal[(cereal.mfr=='G') & (cereal.calories > 100)].shape[0]

17

In [ ]:
## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.

## Individual Exercise 3

- Create a 3x3x3 array that contains all random numbers.
- Using the previous array, square all the numbers in the array.


In [ ]:
import numpy as np

In [ ]:
## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.
matrix = np.random.rand(3,3,3)
print(matrix)

[[[0.88176427 0.55384419 0.53554638]
  [0.41858411 0.91411363 0.63505308]
  [0.92801413 0.70200131 0.13760509]]

 [[0.19445213 0.40328004 0.22641921]
  [0.20896569 0.24045938 0.28832672]
  [0.75406416 0.6517756  0.23759225]]

 [[0.57512734 0.85787799 0.91919656]
  [0.02078952 0.08395423 0.65342699]
  [0.49378448 0.08427684 0.22244721]]]


In [ ]:
matrix * matrix

array([[[7.77508222e-01, 3.06743383e-01, 2.86809925e-01],
        [1.75212655e-01, 8.35603726e-01, 4.03292415e-01],
        [8.61210226e-01, 4.92805845e-01, 1.89351606e-02]],

       [[3.78116295e-02, 1.62634793e-01, 5.12656587e-02],
        [4.36666581e-02, 5.78207139e-02, 8.31323003e-02],
        [5.68612759e-01, 4.24811436e-01, 5.64500753e-02]],

       [[3.30771455e-01, 7.35954643e-01, 8.44922318e-01],
        [4.32204052e-04, 7.04831226e-03, 4.26966831e-01],
        [2.43823108e-01, 7.10258607e-03, 4.94827618e-02]]])

In [ ]:
matrix ** 2

array([[[7.77508222e-01, 3.06743383e-01, 2.86809925e-01],
        [1.75212655e-01, 8.35603726e-01, 4.03292415e-01],
        [8.61210226e-01, 4.92805845e-01, 1.89351606e-02]],

       [[3.78116295e-02, 1.62634793e-01, 5.12656587e-02],
        [4.36666581e-02, 5.78207139e-02, 8.31323003e-02],
        [5.68612759e-01, 4.24811436e-01, 5.64500753e-02]],

       [[3.30771455e-01, 7.35954643e-01, 8.44922318e-01],
        [4.32204052e-04, 7.04831226e-03, 4.26966831e-01],
        [2.43823108e-01, 7.10258607e-03, 4.94827618e-02]]])

In [ ]:
np.square(matrix)

array([[[7.77508222e-01, 3.06743383e-01, 2.86809925e-01],
        [1.75212655e-01, 8.35603726e-01, 4.03292415e-01],
        [8.61210226e-01, 4.92805845e-01, 1.89351606e-02]],

       [[3.78116295e-02, 1.62634793e-01, 5.12656587e-02],
        [4.36666581e-02, 5.78207139e-02, 8.31323003e-02],
        [5.68612759e-01, 4.24811436e-01, 5.64500753e-02]],

       [[3.30771455e-01, 7.35954643e-01, 8.44922318e-01],
        [4.32204052e-04, 7.04831226e-03, 4.26966831e-01],
        [2.43823108e-01, 7.10258607e-03, 4.94827618e-02]]])

## Indivdual Exercise 4

- Create a new array using `arange` this array should contain a total of 4 values.
- Select only values in index 2 and index 4.
- Change the value of index 3 to 99

In [ ]:
## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.

In [ ]:
new_array = np.arange(4)

In [ ]:
print(new_array)

[0 1 2 3]


In [ ]:
print(new_array[[1,3]])

[1 3]


In [ ]:
new_array[2] = 99
print(new_array)

[ 0  1 99  3]


## Individual Exercise 5

- Create a new 4x4 array.
- Select and print only the first two rows.
- Select and print only the last two columns.
- Select only the last two rows and first two columns.
- Reshape the array into a 8x2 array.

In [ ]:
## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.
arr = np.random.rand(4,4)
print(arr)

[[0.65175823 0.75342331 0.88948371 0.88257008]
 [0.83124117 0.11229009 0.70028505 0.1394133 ]
 [0.9574174  0.83850127 0.09010645 0.79134991]
 [0.00848729 0.1536615  0.3123916  0.88846591]]


In [ ]:
arr[0:2,]

array([[0.65175823, 0.75342331, 0.88948371, 0.88257008],
       [0.83124117, 0.11229009, 0.70028505, 0.1394133 ]])

In [ ]:
arr[:, -2:]

array([[0.88948371, 0.88257008],
       [0.70028505, 0.1394133 ],
       [0.09010645, 0.79134991],
       [0.3123916 , 0.88846591]])

In [ ]:
arr[-2:, 0:2]

array([[0.9574174 , 0.83850127],
       [0.00848729, 0.1536615 ]])

In [ ]:
arr.reshape(8,2)

array([[0.65175823, 0.75342331],
       [0.88948371, 0.88257008],
       [0.83124117, 0.11229009],
       [0.70028505, 0.1394133 ],
       [0.9574174 , 0.83850127],
       [0.09010645, 0.79134991],
       [0.00848729, 0.1536615 ],
       [0.3123916 , 0.88846591]])