In [5]:
def fetch_data():
  import os, shutil
  cwd = os.getcwd()
  if os.path.exists("CosmicAI_WinterSchool"):
    shutil.rmtree("CosmicAI_WinterSchool")
  !git clone https://github.com/aliawofford9317/CosmicAI_WinterSchool.git
  for file in os.listdir("CosmicAI_WinterSchool"):
    if file.endswith((".txt",".csv")):
      shutil.copy("CosmicAI_WinterSchool/{}".format(file),cwd)
fetch_data()

PermissionError: [WinError 5] Access is denied: 'CosmicAI_WinterSchool\\.git\\objects\\pack\\pack-5d35c89f2f292212c0f1c92aebbb2fd1fd4d8c1a.idx'

## Exercise 1

1. Create a new random integer array with Numpy functions. Use a random seed to guarantee the same array every time. Array must be of size (20, 5).

2. Calculate the average value of the second column of the array created in exercise 1. Calculate the sum of all elements in columns 3 and 4. You can use built in ufuncs and indexing.


In [7]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn
!pip install tensorflow
!pip install keras
!pip install opencv-python
!pip install opencv-python-headless
!pip install pillow
!pip install scipy
!pip install astropy
!pip install astroquery
!pip install astrophysics
!pip install astropy-helpers
!pip install astropy-visualization
!pip install astropy-visualization-mpl
!pip install astropy-visualization-mpl-helpers

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   --------- ------------------------------ 3.1/12.8 MB 19.4 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 39.0 MB/s  0:00:00



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.0 MB 9.0 MB/s eta 0:00:02
   ---------------------------------------- 11.0/11.0 MB 33.8 MB/s  0:00:00

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------------------------------ --- 7.3/8.1 MB 39.9 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 33.6 MB/s  0:00:00
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 56.4 MB/s  0:00:00
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 7.0/7.0 MB 65.2 MB/s  0:00:00

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ----


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.0 MB 15.3 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 30.0 MB/s  0:00:00
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   -------- ------------------------------- 7.9/38.5 MB 40.4 MB/s eta 0:00:01
   ------------------- -------------------- 18.4/38.5 MB 43.9 MB/s eta 0:00:01
   ------------------------------ --------- 29.1/38.5 MB 46.1 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 48.6 MB/s eta 0:00:01
   ---------------------------------------- 38.5/38.5 MB 40.5 MB/s  0:00:00

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- --


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/332.0 MB ? eta -:--:--
   ---------------------------------------- 1.8/332.0 MB 12.4 MB/s eta 0:00:27
   - -------------------------------------- 13.1/332.0 MB 38.3 MB/s eta 0:00:09
   --- ------------------------------------ 27.3/332.0 MB 49.5 MB/s eta 0:00:07
   ----- ---------------------------------- 45.4/332.0 MB 59.3 MB/s eta 0:00:05
   ------- -------------------------------- 65.8/332.0 MB 67.2 MB/s eta 0:00:04
   ---------- ----------------------------- 88.1/332.0 MB 74.0 MB/s eta 0:00:04
   ------------ -------------------------- 108.0/332.0 MB 76.9 MB/s eta 0:00:03
   --------------- ----------------------- 128.5/332.0 MB 79.2 MB/s eta 0:00:03
   ----------------- --------------------- 149.4/332.0 MB 81.5 MB/s eta 0:00:03
   ------------------- ------------------- 170.1/332.0 MB 83.0 MB/s eta 0:00:02
   --------------------- ----------------- 187.2/332

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\anana\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\tensorflow\\include\\external\\com_github_grpc_grpc\\src\\core\\ext\\filters\\fault_injection\\fault_injection_service_config_parser.h'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/39.0 MB ? eta -:--:--
   --- ------------------------------------ 3.1/39.0 MB 20.0 MB/s eta 0:00:02
   --------------- ------------------------ 15.5/39.0 MB 42.0 MB/s eta 0:00:01
   -------------------------- ------------- 26.0/39.0 MB 44.7 MB/s eta 0:00:01
   ------------------------------------- -- 36.7/39.0 MB 46.1 MB/s eta 0:00:01
   ---------------------------------------  38.5/39.0 MB 38.4 MB/s eta 0:00:01
   ---------------------------------------  38.8/39.0 MB 36.1 MB/s eta 0:00:01
   ---------------------------------------- 39.0/39.0 MB 29.5 MB/s  0:00:01
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------------------------ --------------- 7.9/12.6 MB 39.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 39.6 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 39.6 MB/s eta 0:00:


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/38.9 MB ? eta -:--:--
    --------------------------------------- 0.8/38.9 MB 7.3 MB/s eta 0:00:06
   ---------- ----------------------------- 10.5/38.9 MB 31.8 MB/s eta 0:00:01
   ------------------------ --------------- 24.1/38.9 MB 44.4 MB/s eta 0:00:01
   ---------------------------------------  38.8/38.9 MB 53.6 MB/s eta 0:00:01
   ---------------------------------------  38.8/38.9 MB 53.6 MB/s eta 0:00:01
   ---------------------------------------  38.8/38.9 MB 53.6 MB/s eta 0:00:01
   ---------------------------------------- 38.9/38.9 MB 30.2 MB/s  0:00:01



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/6.4 MB ? eta -:--:--
   ------ --------------------------------- 1.0/6.4 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 6.4/6.4 MB 24.4 MB/s  0:00:00
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 10.3 MB/s  0:00:00

   ---------------------------------------- 0/4 [PyYAML]
   ---------- ----------------------------- 1/4 [pyerfa]
   -------------------- ------------------- 2/4 [astropy-iers-data]
   ------------------------------ --------- 3/4 [astropy]
   ------------------------------ --------- 3/4 [astropy]
   ------------------------------ --------- 3/4 [astropy]
   ------------------------------ --------- 3/4 [astropy]
   ------------------------------ --------- 3/4 [astropy]
   ------------------------------ --------- 3/4 [astropy]
   --------------------------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.1 MB 15.2 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 37.7 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 37.7 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 17.1 MB/s  0:00:00
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 10.7 MB/s  0:00:00

   --- ------------------------------------  1/12 [soupsieve]
   ------ ---------------------------------  2/12 [pywin32-ctypes]
   ------ ---------------------------------  2/12 [pywin32-ctypes]
   ------ ---------------------------------  2/12 [pywin32-ctypes]
   ------ ---------------------------------  2/12 [pywin32-ctypes]
   ---------- -----------------------------  3/12 [more-itertools]


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement astrophysics (from versions: none)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for astrophysics


Defaulting to user installation because normal site-packages is not writeable
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      <string>:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      C:\Users\anana\AppData\Local\Temp\pip-install-e1r10wyo\astropy-helpers_9244f817716f4d7bae0c06d731bef32a\astropy_helpers\version_helpers.py:31: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
        import pkg_resources
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "C:\Program Files\Win

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement astropy-visualization (from versions: none)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for astropy-visualization


Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement astropy-visualization-mpl (from versions: none)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for astropy-visualization-mpl


Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement astropy-visualization-mpl-helpers (from versions: none)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\anana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for astropy-visualization-mpl-helpers


In [8]:
import numpy as np

# ------------------------------------------
# 1. Create random integer array (20 × 5)
# ------------------------------------------
np.random.seed(42)  # ensures same result every time

# Array of integers from 0–100 (you can change the range)
arr = np.random.randint(0, 100, size=(20, 5))

print("Array (20 x 5):")
print(arr)

# ------------------------------------------------------
# 2. Calculate required statistics
# ------------------------------------------------------

# Average of the SECOND column (index 1)
avg_second_col = np.mean(arr[:, 1])

# Sum of all elements in columns 3 AND 4 (indexes 2 and 3)
sum_cols_3_4 = np.sum(arr[:, 2:4])

print("\nAverage of second column:", avg_second_col)
print("Sum of columns 3 and 4:", sum_cols_3_4)

Array (20 x 5):
[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]
 [75 57 21 88 48]
 [90 58 41 91 59]
 [79 14 61 61 46]
 [61 50 54 63  2]
 [50  6 20 72 38]
 [17  3 88 59 13]
 [ 8 89 52  1 83]
 [91 59 70 43  7]
 [46 34 77 80 35]
 [49  3  1  5 53]
 [ 3 53 92 62 17]
 [89 43 33 73 61]
 [99 13 94 47 14]
 [71 77 86 61 39]
 [84 79 81 52 23]]

Average of second column: 48.75
Sum of columns 3 and 4: 2194


## Exercise 2

We will now use a simple IoT readings dataset for this exercise. This dataset contains IoT temperature readings, where the reading was made (room) and location (reading was outside or inside a room).

3. Open the data file `IOT-temp.csv` inside the `iotdata-compressed` file, you will need some program like 7zip or Winrar to uncompress this `iotdata-compressed` folder. Open this file with Pandas and create a new Dataframe with this data. Show the first 10 rows of data. Show the last 10 rows of data. Show data points for index 300 to 350.


4. Create a new dataframe from index 1000 to 2000. Rename column `out/in` to `location`. Rename colum `room_id/id` to `room` How many of these readings were made outside? How many were inside?


5. Split your new dataframe into readings that were made inside and readings that were made outside. Create a new dataframe with only inside readings. Create a new dataframe only with outside readings. Print the mean value of the temperature for both new dataframes.


6. Save both dataframes created in exercise 5 to `csv` files.

More information about the dataset for exercises 3 and 4 in [this link](https://www.kaggle.com/datasets/atulanandjha/temperature-readings-iot-devices)

In [9]:
import pandas as pd

# -------------------------------
# 1. Load the CSV file
# -------------------------------
df = pd.read_csv("IOT-temp.csv")

# Standardize capitalization for consistency
df["out/in"] = df["out/in"].str.lower()

# -------------------------------
# 2. Show first 10 rows
# -------------------------------
print("First 10 rows:")
print(df.head(10))

# -------------------------------
# 3. Show last 10 rows
# -------------------------------
print("\nLast 10 rows:")
print(df.tail(10))

# -------------------------------
# 4. Show rows 300 to 350
# -------------------------------
print("\nRows 300 to 350:")
print(df.iloc[300:351])

# -------------------------------
# 5. Create new dataframe index 1000–2000
# -------------------------------
df2 = df.iloc[1000:2001].copy()

# Rename columns
df2 = df2.rename(columns={
    "out/in": "location",
    "room_id/id": "room"
})

# -------------------------------
# 6. Count inside vs outside
# -------------------------------
outside_count = (df2["location"] == "out").sum()
inside_count = (df2["location"] == "in").sum()

print("\nNumber of OUTSIDE readings:", outside_count)
print("Number of INSIDE readings:", inside_count)

# -------------------------------
# 7. Split into inside/outside dataframes
# -------------------------------
inside_df = df2[df2["location"] == "in"]
outside_df = df2[df2["location"] == "out"]

# -------------------------------
# 8. Print mean temperatures
# -------------------------------
print("\nMean temperature (INSIDE):", inside_df["temp"].mean())
print("Mean temperature (OUTSIDE):", outside_df["temp"].mean())

# -------------------------------
# 9. Save new dataframes to CSV
# -------------------------------
inside_df.to_csv("inside_readings.csv", index=False)
outside_df.to_csv("outside_readings.csv", index=False)

print("\nFiles saved:")
print("inside_readings.csv")
print("outside_readings.csv")

## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.

First 10 rows:
                                    id  room_id/id        noted_date  temp  \
0  __export__.temp_log_196134_bd201015  Room Admin  08-12-2018 09:30    29   
1  __export__.temp_log_196131_7bca51bc  Room Admin  08-12-2018 09:30    29   
2  __export__.temp_log_196127_522915e3  Room Admin  08-12-2018 09:29    41   
3  __export__.temp_log_196128_be0919cf  Room Admin  08-12-2018 09:29    41   
4  __export__.temp_log_196126_d30b72fb  Room Admin  08-12-2018 09:29    31   
5  __export__.temp_log_196125_b0fa0b41  Room Admin  08-12-2018 09:29    31   
6  __export__.temp_log_196121_01544d45  Room Admin  08-12-2018 09:28    29   
7  __export__.temp_log_196122_f8b80a9f  Room Admin  08-12-2018 09:28    29   
8  __export__.temp_log_196111_6b7a0848  Room Admin  08-12-2018 09:26    29   
9  __export__.temp_log_196112_e134aebd  Room Admin  08-12-2018 09:26    29   

  out/in  
0     in  
1     in  
2    out  
3    out  
4     in  
5     in  
6     in  
7     in  
8     in  
9     in  

Last

## Exercise 3:

Use the provided code below to complete the exercise.

-Compute the dot product of v1 and v2.

-Compute the Euclidean norm of each vector.

-Compute the element-wise sum and element-wise product of the vectors.

In [10]:
#Create two NumPy vectors:

v1 = np.array([2, 4, 6])
v2 = np.array([1, 3, 5])
## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.

In [11]:
#Solution

import numpy as np

u = np.array([3, -1, 2])
v = np.array([1, 4, -2])

# 1. Orthogonality
dot_uv = np.dot(u, v)
orthogonal = (dot_uv == 0)

# 2. Projection of u onto v
proj_u_on_v = (np.dot(u, v) / np.dot(v, v)) * v

# 3. Projection of v onto u
proj_v_on_u = (np.dot(v, u) / np.dot(u, u)) * u

# 4. Parallel & perpendicular components of u wrt v
u_parallel_v = proj_u_on_v
u_perp_v = u - u_parallel_v

dot_uv, orthogonal, proj_u_on_v, proj_v_on_u, u_parallel_v, u_perp_v


(np.int64(-5),
 np.False_,
 array([-0.23809524, -0.95238095,  0.47619048]),
 array([-1.07142857,  0.35714286, -0.71428571]),
 array([-0.23809524, -0.95238095,  0.47619048]),
 array([ 3.23809524, -0.04761905,  1.52380952]))

## Exercise 4:
Use the provided code below to complete the exercise.

-Compute the determinant of A.

-Compute the condition number of A.

-Solve the system  𝐴𝑥=𝑏.

-Verify the solution by computing 𝐴𝑥 and comparing to b using np.allclose.

-Bonus: Discuss what a high condition number implies about the accuracy of the solution.

In [12]:
# Create a 3×3 matrix:

A = np.array([
    [3, 5, 1],
    [2, 4, 7],
    [6, 8, 9]
])


## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.

In [13]:
#Solution

np.random.seed(7)
A = np.random.randn(5, 5)
b = np.random.randn(5)

# 1. Determinant
det_A = np.linalg.det(A)

# 2. Condition number
cond_A = np.linalg.cond(A)

# 3. Solve Ax = b
x = np.linalg.solve(A, b)

# 4. Verification
verified = np.allclose(A @ x, b)

det_A, cond_A, x, verified


(np.float64(-4.025652684271792),
 np.float64(10.47881856714073),
 array([ 1.7099303 ,  7.40114702, -1.21240189, -2.39406638, -0.15530466]),
 True)

## Exercise 5:

Use the provided code below to complete the exercise.

-Compute the rank of M.

-Compute the SVD decomposition: U, S, Vt.

-Reconstruct M from the SVD components.

- Compute the Frobenius norm of the reconstruction error.

In [14]:
M = np.array([
    [2, 0, 1],
    [1, 3, 4],
    [0, 1, 2]
])

## USE THIS SPACE TO PASTE YOUR SOLUTIONS FOR THE ABOVE EXERCISE.

In [15]:
#Solution

M = np.array([
    [2, 0, 1],
    [1, 3, 4],
    [0, 1, 2]
])

# 1. Rank
rank_M = np.linalg.matrix_rank(M)

# 2. Compute SVD
U, S, Vt = np.linalg.svd(M)

# 3. Reconstruction
S_matrix = np.zeros_like(M, dtype=float)
np.fill_diagonal(S_matrix, S)
M_reconstructed = U @ S_matrix @ Vt

# 4. Reconstruction error
error = np.linalg.norm(M - M_reconstructed, ord='fro')

rank_M, U, S, Vt, error


(np.int64(3),
 array([[-0.22605201,  0.96279355,  0.14808469],
        [-0.8970194 , -0.14646881, -0.41701688],
        [-0.37981138, -0.22710234,  0.89675406]]),
 array([5.67182376, 1.90143866, 0.46362298]),
 array([[-0.23786413, -0.54142542, -0.80639889],
        [ 0.93566957, -0.35052867, -0.04064625],
        [-0.26065901, -0.76419118,  0.58997349]]),
 np.float64(2.7396180231804076e-15))

## Exercise 6:

Use the provided code below to complete the exercise.

-Compute the eigenvalues and eigenvectors of Q.

-Diagonalize $\mathbf{Q}$ by computing $P D P^{-1}$.
-Compute $Q^5$ using the eigen-decomposition:

Q^5 = P D^5 P^{-1}

-Compare the two results with np.allclose.




In [17]:
Q = np.array([
    [6, -1],
    [2,  3]
])

# 1. Eigenvalues & vectors
vals, vecs = np.linalg.eig(Q)

# 2. Diagonalization
P = vecs
D = np.diag(vals)
Pinv = np.linalg.inv(P)

PDPinv = P @ D @ Pinv   # reconstruct Q

# 3. Direct Q^5
Q5_direct = np.linalg.matrix_power(Q, 5)

# 4. Eigen-decomposition Q^5
D5 = np.diag(vals**5)
Q5_eig = P @ D5 @ Pinv

# 5. Compare
compare = np.allclose(Q5_direct, Q5_eig)

vals, vecs, PDPinv, Q5_direct, Q5_eig, compare

(array([5., 4.]),
 array([[0.70710678, 0.4472136 ],
        [0.70710678, 0.89442719]]),
 array([[ 6., -1.],
        [ 2.,  3.]]),
 array([[ 5226, -2101],
        [ 4202, -1077]]),
 array([[ 5226., -2101.],
        [ 4202., -1077.]]),
 True)